# Use OpenJDK 17 as the base image
FROM openjdk:17

# Expose the application port
EXPOSE 8080

# Set environment variables
ENV SPRING_PROFILES_ACTIVE=bootstrap
ENV HIBERNATE_EJB_NAMING_STRATEGY=org.hibernate.cfg.ImprovedNamingStrategy
ENV HIBERNATE_SHOW_SQL=false
ENV JAVA_HOME=/usr/java/openjdk-17
ENV JAVA_VERSION=17.0.2
ENV JWT_PRIVATE_KEY=classpath:rsa.private.key
ENV JWT_PUBLIC_KEY=classpath:rsa.public.key
ENV LANG=C.UTF-8
ENV LOGGING_LEVEL_COM_EXAMPLE_DEMO=DEBUG
ENV PATH=/usr/java/openjdk-17/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
ENV SPRING_DATASOURCE_PASSWORD=mysqlpass
ENV SPRING_DATASOURCE_URL=jdbc:h2:~/StorageApi/db;MV_STORE=FALSE;AUTO_SERVER=true;
ENV SPRING_DATASOURCE_USERNAME=mysqluser
ENV SPRING_H2_CONSOLE_ENABLED=true
ENV SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
ENV SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
ENV SPRING_JPA_GENERATE_DDL=true
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=update
ENV SPRING_JPA_HIBERNATE_FORMAT_SQL=true
ENV SPRING_JPA_SHOW_SQL=false
ENV SPRING_SECURITY_ENABLED=false
ENV SPRING_SERVLET_MULTIPART_ENABLED=true
ENV SPRING_SERVLET_MULTIPART_FILE_SIZE_THRESHOLD=2KB
ENV SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=200MB
ENV SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=215MB
ENV SPRINGDOC_API_DOCS_ENABLED=true
ENV SPRINGDOC_API_DOCS_PATH=/api-docs
ENV SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui

# Copy the jar file to the container
COPY StorageApi-0.0.1-SNAPSHOT.jar storageapi.jar

# Define the entry point for the container
ENTRYPOINT ["java", "-jar", "/storageapi.jar"]
